### ISSUE TITLE
License for this repository?

### ISSUE THREAD

**Issue by gnattu** [saagarjha/MacCast#1]
I would like to know if I could integrate derived code into my own products depending on the license. Thank you for your work.

**Comment by saagarjha** [comment]
This project isn’t ready for use yet, so I’m going to keep it unlicensed for now. I expect that once I’ve worked on it more it will be available under some sort of copyleft license. If possible I might move some of the code out into their own libraries with weaker licenses. Do you have something specific in mind?

**Comment by maxxfrazer** [comment]
Please add a license! Many employers won’t entertain letting employees use or try any software that doesn’t have a license.

**Comment by saagarjha** [comment]
You might be disappointed if you try to actually use this for real work, since it's not quite ready for that yet. But feel free to play around with it and let me know what you think. I'm not Oracle, I won't charge you fees if I find it running on your computer ;) There's now a license that affirms as such for your employer's lawyers.
